### ISSUE TITLE
Include ML model of origin in the perovskitedata.csv

### ISSUE THREAD

**Issue by cinaljess** [darkreactions/ESCALATE_report#27]
It would be a useful feature to know the ML model of origin from which each experiment was suggested from. This would enable learning on just a single model if desired, not incorporating training data suggested by other models.

Add a column to the perovskitedata.csv file that contains the name of the model of origin, eg from the 'Name' column on escalation.

**Comment by ipendlet** [comment]
Column added _raw_modelname to the dataset which reports this information where available.  Initial copy of this dataframe will be upload for crank 0026 on versioned data repo
